/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalImprintRouteImport } from './routes/legal.imprint'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalComplaintsRouteImport } from './routes/legal.complaints'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AppTrainingRouteImport } from './routes/app.training'
import { Route as AppTemperatureRouteImport } from './routes/app.temperature'
import { Route as AppSuppliersRouteImport } from './routes/app.suppliers'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRecipesRouteImport } from './routes/app.recipes'
import { Route as AppInspectionRouteImport } from './routes/app.inspection'
import { Route as AppHaccpRouteImport } from './routes/app.haccp'
import { Route as AppCleaningRouteImport } from './routes/app.cleaning'
import { Route as AppChecksRouteImport } from './routes/app.checks'
import { Route as AppAlertsRouteImport } from './routes/app.alerts'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LegalRoute,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LegalRoute,
} as any)
const LegalImprintRoute = LegalImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => LegalRoute,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => LegalRoute,
} as any)
const LegalComplaintsRoute = LegalComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => LegalRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AppTrainingRoute = AppTrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => AppRoute,
} as any)
const AppTemperatureRoute = AppTemperatureRouteImport.update({
  id: '/temperature',
  path: '/temperature',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRecipesRoute = AppRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => AppRoute,
} as any)
const AppInspectionRoute = AppInspectionRouteImport.update({
  id: '/inspection',
  path: '/inspection',
  getParentRoute: () => AppRoute,
} as any)
const AppHaccpRoute = AppHaccpRouteImport.update({
  id: '/haccp',
  path: '/haccp',
  getParentRoute: () => AppRoute,
} as any)
const AppCleaningRoute = AppCleaningRouteImport.update({
  id: '/cleaning',
  path: '/cleaning',
  getParentRoute: () => AppRoute,
} as any)
const AppChecksRoute = AppChecksRouteImport.update({
  id: '/checks',
  path: '/checks',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertsRoute = AppAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/legal': typeof LegalRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/checks': typeof AppChecksRoute
  '/app/cleaning': typeof AppCleaningRoute
  '/app/haccp': typeof AppHaccpRoute
  '/app/inspection': typeof AppInspectionRoute
  '/app/recipes': typeof AppRecipesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/temperature': typeof AppTemperatureRoute
  '/app/training': typeof AppTrainingRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/legal/complaints': typeof LegalComplaintsRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/imprint': typeof LegalImprintRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/legal': typeof LegalRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/checks': typeof AppChecksRoute
  '/app/cleaning': typeof AppCleaningRoute
  '/app/haccp': typeof AppHaccpRoute
  '/app/inspection': typeof AppInspectionRoute
  '/app/recipes': typeof AppRecipesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/temperature': typeof AppTemperatureRoute
  '/app/training': typeof AppTrainingRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/legal/complaints': typeof LegalComplaintsRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/imprint': typeof LegalImprintRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/app': typeof AppIndexRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/legal': typeof LegalRouteWithChildren
  '/login': typeof LoginRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/alerts': typeof AppAlertsRoute
  '/app/checks': typeof AppChecksRoute
  '/app/cleaning': typeof AppCleaningRoute
  '/app/haccp': typeof AppHaccpRoute
  '/app/inspection': typeof AppInspectionRoute
  '/app/recipes': typeof AppRecipesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/suppliers': typeof AppSuppliersRoute
  '/app/temperature': typeof AppTemperatureRoute
  '/app/training': typeof AppTrainingRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/legal/complaints': typeof LegalComplaintsRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/imprint': typeof LegalImprintRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/app/': typeof AppIndexRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/blog'
    | '/legal'
    | '/login'
    | '/sitemap.xml'
    | '/app/alerts'
    | '/app/checks'
    | '/app/cleaning'
    | '/app/haccp'
    | '/app/inspection'
    | '/app/recipes'
    | '/app/settings'
    | '/app/suppliers'
    | '/app/temperature'
    | '/app/training'
    | '/blog/$slug'
    | '/legal/complaints'
    | '/legal/cookies'
    | '/legal/imprint'
    | '/legal/privacy'
    | '/legal/terms'
    | '/app/'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/legal'
    | '/login'
    | '/sitemap.xml'
    | '/app/alerts'
    | '/app/checks'
    | '/app/cleaning'
    | '/app/haccp'
    | '/app/inspection'
    | '/app/recipes'
    | '/app/settings'
    | '/app/suppliers'
    | '/app/temperature'
    | '/app/training'
    | '/blog/$slug'
    | '/legal/complaints'
    | '/legal/cookies'
    | '/legal/imprint'
    | '/legal/privacy'
    | '/legal/terms'
    | '/app'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/blog'
    | '/legal'
    | '/login'
    | '/sitemap.xml'
    | '/app/alerts'
    | '/app/checks'
    | '/app/cleaning'
    | '/app/haccp'
    | '/app/inspection'
    | '/app/recipes'
    | '/app/settings'
    | '/app/suppliers'
    | '/app/temperature'
    | '/app/training'
    | '/blog/$slug'
    | '/legal/complaints'
    | '/legal/cookies'
    | '/legal/imprint'
    | '/legal/privacy'
    | '/legal/terms'
    | '/app/'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  LegalRoute: typeof LegalRouteWithChildren
  LoginRoute: typeof LoginRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/imprint': {
      id: '/legal/imprint'
      path: '/imprint'
      fullPath: '/legal/imprint'
      preLoaderRoute: typeof LegalImprintRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof LegalRoute
    }
    '/legal/complaints': {
      id: '/legal/complaints'
      path: '/complaints'
      fullPath: '/legal/complaints'
      preLoaderRoute: typeof LegalComplaintsRouteImport
      parentRoute: typeof LegalRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/app/training': {
      id: '/app/training'
      path: '/training'
      fullPath: '/app/training'
      preLoaderRoute: typeof AppTrainingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/temperature': {
      id: '/app/temperature'
      path: '/temperature'
      fullPath: '/app/temperature'
      preLoaderRoute: typeof AppTemperatureRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/suppliers': {
      id: '/app/suppliers'
      path: '/suppliers'
      fullPath: '/app/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/recipes': {
      id: '/app/recipes'
      path: '/recipes'
      fullPath: '/app/recipes'
      preLoaderRoute: typeof AppRecipesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inspection': {
      id: '/app/inspection'
      path: '/inspection'
      fullPath: '/app/inspection'
      preLoaderRoute: typeof AppInspectionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/haccp': {
      id: '/app/haccp'
      path: '/haccp'
      fullPath: '/app/haccp'
      preLoaderRoute: typeof AppHaccpRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cleaning': {
      id: '/app/cleaning'
      path: '/cleaning'
      fullPath: '/app/cleaning'
      preLoaderRoute: typeof AppCleaningRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/checks': {
      id: '/app/checks'
      path: '/checks'
      fullPath: '/app/checks'
      preLoaderRoute: typeof AppChecksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alerts': {
      id: '/app/alerts'
      path: '/alerts'
      fullPath: '/app/alerts'
      preLoaderRoute: typeof AppAlertsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAlertsRoute: typeof AppAlertsRoute
  AppChecksRoute: typeof AppChecksRoute
  AppCleaningRoute: typeof AppCleaningRoute
  AppHaccpRoute: typeof AppHaccpRoute
  AppInspectionRoute: typeof AppInspectionRoute
  AppRecipesRoute: typeof AppRecipesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppTemperatureRoute: typeof AppTemperatureRoute
  AppTrainingRoute: typeof AppTrainingRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertsRoute: AppAlertsRoute,
  AppChecksRoute: AppChecksRoute,
  AppCleaningRoute: AppCleaningRoute,
  AppHaccpRoute: AppHaccpRoute,
  AppInspectionRoute: AppInspectionRoute,
  AppRecipesRoute: AppRecipesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppTemperatureRoute: AppTemperatureRoute,
  AppTrainingRoute: AppTrainingRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface LegalRouteChildren {
  LegalComplaintsRoute: typeof LegalComplaintsRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalImprintRoute: typeof LegalImprintRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

const LegalRouteChildren: LegalRouteChildren = {
  LegalComplaintsRoute: LegalComplaintsRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalImprintRoute: LegalImprintRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
}

const LegalRouteWithChildren = LegalRoute._addFileChildren(LegalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  LegalRoute: LegalRouteWithChildren,
  LoginRoute: LoginRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
